"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Download, Share2, AlertCircle, CheckCircle } from "lucide-react";
import { DAWN_LINKS, HARDWARE_FACTS, DISCLAIMERS } from "@/data/dawnFacts";
import DataDisclaimer from "@/components/DataDisclaimer";
import type { FitResult } from "@/types/fitResult";
import type { TabId } from "@/app/page";

interface MyPitchProps {
  fitResult: FitResult | null;
  onTabChange: (tab: TabId) => void;
}

function buildPitchText(result: FitResult): string {
  const rec = result.matchResult.recommendation;
  const loc = result.locationName || "your location";
  const now = new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" });

  return `DAWN INTERNET — COMMUNITY OPPORTUNITY PITCH
Generated by DawnBeacon (independent community tool) • ${now}

⚠ DISCLAIMER: This document is prepared by DawnBeacon, an independent, unofficial community tool.
DawnBeacon is NOT affiliated with or endorsed by DAWN Internet. All figures shown trace to
DAWN's published sources. Hardware reward amounts are not published as a specific formula —
qualitative factors only are shown.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LOCATION: ${loc}
SUGGESTED FIT: ${rec}
CONFIDENCE: ${result.matchResult.confidence}
ASSESSMENT DATE: ${now}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHAT IS DAWN INTERNET?
DAWN (Decentralized Autonomous Wireless Network) is a user-owned wireless DePIN network
that aims to let property owners and individuals participate in a decentralized internet
coverage layer. Learn more: ${DAWN_LINKS.mainSite}

ABOUT THE VALIDATOR EXTENSION (free, no hardware required):
Any internet user can participate by installing the DAWN Validator Extension:
${DAWN_LINKS.validatorExtension}

Based on DAWN's published rewards system (${DAWN_LINKS.rewardsSystem}):
• 1,440 reward points available per 24-hour period for staying connected
• Referral Tier A (direct): 20% of their lifetime points, ongoing
• Referral Tier B (their referral): 10% of their lifetime points, ongoing
• Referral Tier C (third level): 5% of their lifetime points, ongoing
• 5,000 points per social platform followed (X, Discord, Telegram)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

HARDWARE OPPORTUNITY (for this location):
${rec === "Black Box"
  ? `BLACK BOX ROUTER
${HARDWARE_FACTS.blackBox.description}

Partner Networks: ${HARDWARE_FACTS.blackBox.partnerNetworks.join(", ")}

Applicable Mechanisms (based on DAWN's published information):
${HARDWARE_FACTS.blackBox.mechanisms.map((m) => "• " + m).join("\n")}

Note: Hardware reward amounts are not published as a specific formula by DAWN.
Qualitative factors only. This location may qualify for these mechanisms.

Purchase: ${DAWN_LINKS.blackBoxStore}`
  : rec === "Antenna"
  ? `ANTENNA / DEPLOYER NETWORK
${HARDWARE_FACTS.antenna.description}

Requirements identified for this location:
${HARDWARE_FACTS.antenna.requirements.map((r) => "• " + r).join("\n")}

Applicable Mechanisms:
${HARDWARE_FACTS.antenna.mechanisms.map((m) => "• " + m).join("\n")}

IMPORTANT — About the Deployer Application Form:
${HARDWARE_FACTS.antenna.deployerFormNote}

Apply here: ${DAWN_LINKS.deployerForm}

Note: Hardware reward amounts are not published as a specific formula by DAWN.`
  : `RECRUIT A BIGGER HOST
This location may be best served by identifying a property owner or business with suitable
premises and bringing them this opportunity. The Deployer program targets operators with
existing or multiple institutional sites.

Resources:
• Black Box store: ${DAWN_LINKS.blackBoxStore}
• Deployer interest form: ${DAWN_LINKS.deployerForm}`}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SOURCES & FURTHER READING:
• DAWN main site: ${DAWN_LINKS.mainSite}
• Rewards System (source of all extension numbers): ${DAWN_LINKS.rewardsSystem}
• Whitepaper (July 2024): ${DAWN_LINKS.whitepaper}
• Validator Extension: ${DAWN_LINKS.validatorExtension}
• Black Box store: ${DAWN_LINKS.blackBoxStore}
• Deployer Application Form: ${DAWN_LINKS.deployerForm}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LANGUAGE GUIDE FOR THIS PITCH:
Use "may qualify," "based on DAWN's published mechanics," "potentially," and similar
hedged language at all times. NEVER use "guaranteed" or "you will earn."
This pitch is informational only — verify all current information directly with DAWN.`;
}

export default function MyPitchTab({ fitResult, onTabChange }: MyPitchProps) {
  const [downloaded, setDownloaded] = useState(false);
  const [downloading, setDownloading] = useState(false);

  if (!fitResult) {
    return (
      <div className="max-w-2xl mx-auto space-y-6">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center"
              style={{ background: "rgba(233,108,56,0.15)", border: "1px solid rgba(233,108,56,0.3)", color: "#E96C38" }}>
              <FileText size={20} />
            </div>
            <h2 className="text-2xl font-bold text-white" style={{ fontFamily: "Space Grotesk, sans-serif" }}>My Pitch</h2>
          </div>
        </motion.div>

        <motion.div
          className="glass-card p-10 text-center space-y-4"
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <div className="w-16 h-16 mx-auto rounded-2xl flex items-center justify-center"
            style={{ background: "rgba(233,108,56,0.1)", border: "1px solid rgba(233,108,56,0.2)" }}>
            <FileText size={28} className="text-[rgba(233,108,56,0.5)]" />
          </div>
          <h3 className="text-lg font-semibold text-white">No Result Yet</h3>
          <p className="text-white/50 text-sm leading-relaxed max-w-md mx-auto">
            Complete <strong className="text-white">Check My Fit</strong> or search a location on the{" "}
            <strong className="text-white">Opportunity Map</strong> first to generate your pitch.
          </p>
          <div className="flex flex-wrap gap-3 justify-center pt-2">
            <button onClick={() => onTabChange("check")} className="btn-primary text-sm px-6 py-2.5">
              Check My Fit →
            </button>
            <button onClick={() => onTabChange("map")} className="btn-secondary text-sm px-6 py-2.5">
              Opportunity Map →
            </button>
          </div>
        </motion.div>
      </div>
    );
  }

  const pitchText = buildPitchText(fitResult);
  const rec = fitResult.matchResult.recommendation;
  const loc = fitResult.locationName || "Your Location";

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 18;
      const contentWidth = pageWidth - margin * 2;
      let y = 20;

      // Header
      doc.setFillColor(233, 108, 56);
      doc.rect(0, 0, pageWidth, 14, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("DawnBeacon — Independent Community Tool (NOT affiliated with DAWN Internet)", margin, 9);

      // Title
      y = 28;
      doc.setTextColor(233, 108, 56);
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("DAWN Internet", margin, y);
      y += 8;
      doc.setFontSize(14);
      doc.setTextColor(50, 50, 50);
      doc.text("Community Opportunity Pitch", margin, y);

      // Location & recommendation
      y += 12;
      doc.setFillColor(250, 246, 242);
      doc.rect(margin, y - 5, contentWidth, 22, "F");
      doc.setTextColor(233, 108, 56);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(`Suggested Fit: ${rec}`, margin + 4, y + 3);
      doc.setTextColor(80, 80, 80);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(`Location: ${loc}`, margin + 4, y + 10);
      doc.text(`Confidence: ${fitResult.matchResult.confidence} | Generated: ${new Date().toLocaleDateString()}`, margin + 4, y + 16);

      // Disclaimer
      y += 28;
      doc.setFillColor(255, 245, 240);
      doc.rect(margin, y, contentWidth, 18, "F");
      doc.setDrawColor(233, 108, 56);
      doc.setLineWidth(0.5);
      doc.rect(margin, y, contentWidth, 18, "S");
      doc.setTextColor(180, 80, 30);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text("⚠ DISCLAIMER", margin + 3, y + 5);
      doc.setFont("helvetica", "normal");
      const disclaimerLines = doc.splitTextToSize(
        "DawnBeacon is NOT affiliated with or endorsed by DAWN Internet. All figures trace to DAWN's published sources. Hardware reward amounts are not published as a specific formula — qualitative factors only.",
        contentWidth - 6
      );
      doc.text(disclaimerLines, margin + 3, y + 10);

      // Body content
      y += 26;
      const lines = pitchText.split("\n");
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);

      for (const line of lines.slice(8)) {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }

        if (line.startsWith("━")) {
          doc.setDrawColor(233, 108, 56);
          doc.setLineWidth(0.3);
          doc.line(margin, y, pageWidth - margin, y);
          y += 4;
          continue;
        }

        if (line.match(/^[A-Z\s&()]+:?\s*$/) && line.length > 3) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(233, 108, 56);
          doc.setFontSize(9.5);
          doc.text(line, margin, y);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(40, 40, 40);
          doc.setFontSize(8.5);
          y += 5.5;
          continue;
        }

        const wrapped = doc.splitTextToSize(line || " ", contentWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 4.5;
      }

      // Footer
      doc.setFontSize(7);
      doc.setTextColor(160, 160, 160);
      doc.text(
        `Generated by DawnBeacon (independent community tool) • Not affiliated with DAWN Internet • ${new Date().toISOString().split("T")[0]}`,
        margin,
        285
      );

      doc.save(`DawnBeacon-Pitch-${loc.replace(/[^a-z0-9]/gi, "_").slice(0, 30)}.pdf`);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    } catch (err) {
      console.error("PDF generation failed:", err);
    }
    setDownloading(false);
  };

  const whatsappText = `DAWN Internet Opportunity — Independent Community Assessment\n\nLocation: ${loc}\nSuggested fit: ${rec} (confidence: ${fitResult.matchResult.confidence})\n\nGenerated by DawnBeacon (unofficial, independent community tool).\n• Extension: ${DAWN_LINKS.validatorExtension}\n• Black Box store: ${DAWN_LINKS.blackBoxStore}\n• Deployer form: ${DAWN_LINKS.deployerForm}\n\n⚠ This is community info, not official DAWN guidance.`;

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center"
            style={{ background: "rgba(233,108,56,0.15)", border: "1px solid rgba(233,108,56,0.3)", color: "#E96C38" }}>
            <FileText size={20} />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white" style={{ fontFamily: "Space Grotesk, sans-serif" }}>My Pitch</h2>
            <p className="text-sm text-white/50">Your shareable opportunity document</p>
          </div>
        </div>
        <DataDisclaimer message={DISCLAIMERS.general + " " + DISCLAIMERS.hardwareRewards} />
      </motion.div>

      {/* Summary card */}
      <motion.div className="glass-card p-5 border border-[rgba(233,108,56,0.3)]"
        initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className="flex items-start justify-between">
          <div>
            <p className="text-xs text-white/40 uppercase tracking-wider mb-1">Your Assessment</p>
            <h3 className="text-2xl font-bold text-gradient" style={{ fontFamily: "Space Grotesk" }}>{rec}</h3>
            <p className="text-sm text-white/50 mt-1">{loc}</p>
          </div>
          <span className="px-3 py-1 rounded-full text-xs"
            style={{ background: "rgba(233,108,56,0.15)", color: "#E96C38", border: "1px solid rgba(233,108,56,0.3)" }}>
            {fitResult.matchResult.confidence} confidence
          </span>
        </div>

        <p className="text-sm text-white/60 mt-3 leading-relaxed">{fitResult.matchResult.reason}</p>

        <div className="mt-3 p-3 rounded-lg text-xs" style={{ background: "rgba(233,108,56,0.08)", border: "1px solid rgba(233,108,56,0.15)" }}>
          <AlertCircle size={12} className="text-[#E96C38] inline mr-1" />
          <strong className="text-[#E96C38]">Deployer form note:</strong>{" "}
          <span className="text-white/60">{HARDWARE_FACTS.antenna.deployerFormNote}</span>
        </div>

        {fitResult.matchResult.caveats.map((c, i) => (
          <div key={i} className="flex items-start gap-2 text-xs text-white/40 mt-2">
            <CheckCircle size={11} className="text-[rgba(233,108,56,0.5)] mt-0.5 flex-shrink-0" />
            <span>{c}</span>
          </div>
        ))}
      </motion.div>

      {/* Pitch preview */}
      <motion.div
        className="glass-card p-5"
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <h4 className="text-sm font-semibold text-white/70 mb-3 uppercase tracking-wider">Pitch Preview</h4>
        <pre className="text-xs text-white/50 leading-relaxed whitespace-pre-wrap font-mono overflow-y-auto max-h-72 pr-2"
          style={{ scrollbarWidth: "thin" }}>
          {pitchText.slice(0, 1200)}...
        </pre>
        <p className="text-[10px] text-white/30 mt-2">Full document available in PDF download</p>
      </motion.div>

      {/* Actions */}
      <motion.div
        className="flex flex-wrap gap-3"
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        <motion.button
          onClick={handleDownload}
          disabled={downloading}
          className="btn-primary flex items-center gap-2 px-6 py-3"
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          {downloading ? (
            <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
              className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full" />
          ) : downloaded ? (
            <CheckCircle size={16} />
          ) : (
            <Download size={16} />
          )}
          {downloaded ? "Downloaded!" : downloading ? "Generating PDF..." : "Download PDF"}
        </motion.button>

        <a
          href={`https://wa.me/?text=${encodeURIComponent(whatsappText)}`}
          target="_blank"
          rel="noopener noreferrer"
          className="btn-secondary flex items-center gap-2 px-6 py-3 no-underline"
        >
          <Share2 size={16} />
          Share on WhatsApp
        </a>
      </motion.div>

      {/* Source links */}
      <motion.div className="glass-card p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}>
        <p className="text-xs text-white/40 mb-3 uppercase tracking-wider">Sources cited in this pitch</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          {[
            { label: "DAWN Rewards System", url: DAWN_LINKS.rewardsSystem },
            { label: "DAWN Whitepaper", url: DAWN_LINKS.whitepaper },
            { label: "Validator Extension", url: DAWN_LINKS.validatorExtension },
            { label: "Deployer Application", url: DAWN_LINKS.deployerForm },
          ].map((link) => (
            <a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer"
              className="flex items-center gap-2 text-xs text-[#E96C38] hover:text-white transition-colors">
              <span>→</span>{link.label}
            </a>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
